// <auto-generated />
using System;
using GestionPaieApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPaieApi.Migrations
{
    [DbContext(typeof(Db_context))]
    [Migration("20241204211852_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionPaieApi.Models.Employe", b =>
                {
                    b.Property<string>("NSS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRecrutement")
                        .HasColumnType("datetime2");

                    b.Property<string>("FonctionPrincipale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NombreEnfants")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PrimeVariable")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Sexe")
                        .HasColumnType("int");

                    b.Property<int?>("SituationFamiliale")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<decimal?>("TauxIndemniteNuisance")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("NSS");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestionPaieApi.Models.ResponsabiliteAdministrative", b =>
                {
                    b.Property<string>("NomResp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmployeNSS")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NomResp");

                    b.HasIndex("EmployeNSS");

                    b.ToTable("ResponsabilitesAdministratives");
                });

            modelBuilder.Entity("GestionPaieApi.Models.ResponsabiliteAdministrative", b =>
                {
                    b.HasOne("GestionPaieApi.Models.Employe", null)
                        .WithMany("Responsabilites")
                        .HasForeignKey("EmployeNSS");
                });

            modelBuilder.Entity("GestionPaieApi.Models.Employe", b =>
                {
                    b.Navigation("Responsabilites");
                });
#pragma warning restore 612, 618
        }
    }
}
